/*
# Create complaints and agent_steps tables for CampusCare AI

1. New Tables
- `complaints`: Stores student-submitted campus complaints and the full AI agent analysis.
  - id (uuid PK)
  - student_name (text)
  - student_id (text)
  - block (text) - building/block location
  - location (text) - specific location within block
  - category (text) - complaint category
  - description (text) - the complaint text
  - issue_summary (text) - generated by analysis agent
  - issue_type (text) - extracted issue type
  - keywords (text[]) - extracted keywords
  - priority (text) - LOW / MEDIUM / HIGH / CRITICAL
  - priority_reason (text) - why this priority
  - department (text) - routed department
  - department_reason (text) - why this department
  - recommended_action (text) - action plan
  - next_step (text) - suggested next step
  - expected_response (text) - expected response time
  - follow_up_message (text) - follow-up agent message
  - final_report (text) - summary agent combined report
  - status (text) - Submitted / Assigned / In Progress / Resolved
  - created_at (timestamptz)
  - updated_at (timestamptz)

- `agent_steps`: Stores individual agent processing steps per complaint (for agent activity visualization).
  - id (uuid PK)
  - complaint_id (uuid FK -> complaints)
  - agent_name (text) - which agent
  - agent_label (text) - display label
  - status (text) - Waiting / Processing / Completed
  - output (text) - agent output summary
  - timestamp (timestamptz)
  - step_order (int) - ordering

2. Security
- Single-tenant app (no sign-in) — RLS enabled, anon+authenticated CRUD allowed since data is intentionally shared/public.
- This is a demo/hackathon app where all visitors share the same complaint data.
*/

CREATE TABLE IF NOT EXISTS complaints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_name text NOT NULL,
  student_id text,
  block text,
  location text NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  issue_summary text,
  issue_type text,
  keywords text[] DEFAULT '{}',
  priority text DEFAULT 'MEDIUM',
  priority_reason text,
  department text,
  department_reason text,
  recommended_action text,
  next_step text,
  expected_response text,
  follow_up_message text,
  final_report text,
  status text NOT NULL DEFAULT 'Submitted',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_complaints" ON complaints;
CREATE POLICY "anon_select_complaints" ON complaints FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_complaints" ON complaints;
CREATE POLICY "anon_insert_complaints" ON complaints FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_complaints" ON complaints;
CREATE POLICY "anon_update_complaints" ON complaints FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_complaints" ON complaints;
CREATE POLICY "anon_delete_complaints" ON complaints FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS agent_steps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id uuid REFERENCES complaints(id) ON DELETE CASCADE,
  agent_name text NOT NULL,
  agent_label text NOT NULL,
  status text NOT NULL DEFAULT 'Waiting',
  output text,
  timestamp timestamptz DEFAULT now(),
  step_order int NOT NULL DEFAULT 0
);

ALTER TABLE agent_steps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_agent_steps" ON agent_steps;
CREATE POLICY "anon_select_agent_steps" ON agent_steps FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_agent_steps" ON agent_steps;
CREATE POLICY "anon_insert_agent_steps" ON agent_steps FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_agent_steps" ON agent_steps;
CREATE POLICY "anon_update_agent_steps" ON agent_steps FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_agent_steps" ON agent_steps;
CREATE POLICY "anon_delete_agent_steps" ON agent_steps FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_priority ON complaints(priority);
CREATE INDEX IF NOT EXISTS idx_complaints_department ON complaints(department);
CREATE INDEX IF NOT EXISTS idx_agent_steps_complaint ON agent_steps(complaint_id);
